export {
  RESTDataSource,
  RequestOptions,
  AugmentedRequest,
  DataSourceFetchResult,
  DataSourceConfig,
  GetRequest,
  PatchRequest,
  PostRequest,
  PutRequest,
  DeleteRequest,
  HeadRequest,
  RequestWithoutBody,
  RequestWithBody,
  DataSourceRequest,
} from './RESTDataSource';
